### PR TITLE
Add optional hardware texture rendering on Android

### PR DESCRIPTION
**Pull request by alexandrius**
This is useful if you want to rotate the rendered image. If renderToHardwareTextureAndroid is enabled image frame cuts of the content for image rotated with transform.

These are screenshots for both enabled and disabled renderToHardwareTextureAndroid
https://imgur.com/a/0ucJbtW

### CODE REVIEW

**Comment by ArtemKolichenkov** [comment]
Thanks for the contribution!
This actually closes #106 

Unfortunately this PR has conflicts now. Can you resolve it? 🙂 

I will apply your fix myself in case you don't follow this repo anymore (trying to fix bugs ASAP here, read #129 if interested). Though I will make sure to mark your contributions once I have allcontributors bot installed in this repo.

**Comment by alexandrius** [comment]
@ArtemKolichenkov Fix

**Comment by ArtemKolichenkov** [comment]
Great! Merging this :)

**Comment by alexandrius** [comment]
@ArtemKolichenkov Any chance of updating https://github.com/ascoders/react-native-image-viewer with updated react-native-image-zoom?

**Comment by ArtemKolichenkov** [comment]
@alexandrius yes. I will do it as soon as I have time, which is either later today or tomorrow :)

**Comment by ArtemKolichenkov** [comment]
@all-contributors please add @alexandrius for code

**Comment by ArtemKolichenkov** [comment]
@alexandrius just released https://github.com/ascoders/react-native-image-viewer v 3.0.1 with updates from this repo.

**Pull request merged**
